# Generated by Django 4.0.6 on 2022-09-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismoBahia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museos',
            name='contacto',
        ),
    ]
